---
instance:
  distribution:
    # renovate: datasource=github-releases depName=fluxcd/flux2
    version: 2.6.3
  cluster:
    networkPolicy: false
  components:
    - source-controller
    - kustomize-controller
    - helm-controller
    - notification-controller
  sync:
    kind: GitRepository
    url: "https://github.com/benwalio/opstimus-prime"
    pullSecret: github-deploy-key
    ref: "refs/heads/main"
    path: kubernetes/flux/cluster
