---
instance:
  distribution:
    # renovate: datasource=github-releases depName=fluxcd/flux2
    version: 2.4.0
  cluster:
    networkPolicy: false
  components:
    - source-controller
    - kustomize-controller
    - helm-controller
    - notification-controller
  sync:
    kind: GitRepository
    url: "ssh://git@github.com/benwalio/opstimus-prime.git"
    pullSecret: github-deploy-key
    ref: "refs/heads/main"
    path: kubernetes/flux/cluster
