---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./github
  - ./prom.yaml
  - ./helmrelease.yaml
  - ./ocirepo.yaml
configMapGenerator:
  - name: flux-instance-helm-values
    files:
      - values.yaml=./helm/values.yaml
configurations:
  - ./helm/kustomizeconfig.yaml
