---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app theme-park
spec:
  interval: 15m
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  maxHistory: 2
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      theme-park:
        annotations:
          reloader.stakater.com/auto: "true"

        replicas: 2
        strategy: RollingUpdate
        pod:
          topologySpreadConstraints:
            - maxSkew: 1
              topologyKey: kubernetes.io/hostname
              whenUnsatisfiable: DoNotSchedule
              labelSelector:
                matchLabels:
                  app.kubernetes.io/name: *app

        containers:
          app:
            image:
              repository: ghcr.io/benwalio/theme-park
              tag: 1.20.1@sha256:7c25b4e01dd05afe3e31f86361e7ffd1d8236c7722761803842dce2103c0ebb3
            resources:
              requests:
                cpu: 5m
                memory: 8M
              limits:
                memory: 52M

    service:
      app:
        controller: *app
        ports:
          http:
            port: 8080

    ingress:
      app:
        enabled: true
        className: internal
        hosts:
          - host: "{{ .Release.Name }}.${SECRET_DOMAIN}"
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
