---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: redlib
spec:
  target:
    name: redlib-secret
    template:
      data:
        REDLIB_DEFAULT_SUBSCRIPTIONS: "{{ .RLIB_SUBS }}+{{ .RLIB_ANIMAL_SUBS }}+{{ .RLIB_FUN_SUBS }}+{{ .RLIB_DIY_SUBS }}"
  dataFrom:
    - extract:
        key: redlib
      sourceRef:
        storeRef:
          kind: ClusterSecretStore
          name: onepassword
