---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app redlib
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.7.2
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 2
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      redlib:
        strategy: RollingUpdate
        containers:
          app:
            image: &img
              repository: quay.io/redlib/redlib
              tag: latest@sha256:fdfa1a6d4e14756c88085957ca0f89ce9bef6991cf3f6a4050f515ef1935e0ff # for JSON HTTP2 fix
            env: &env
              TZ: "${TIMEZONE}"
              REDLIB_SFW_ONLY: "off"
              REDLIB_BANNER: "benwal"
              REDLIB_ROBOTS_DISABLE_INDEXING: "on"
              REDLIB_DEFAULT_THEME: "gruvboxdark"
              REDLIB_DEFAULT_FRONT_PAGE: "default"
              REDLIB_DEFAULT_LAYOUT: "compact"
              REDLIB_DEFAULT_WIDE: "on"
              REDLIB_DEFAULT_POST_SORT: "hot"
              REDLIB_DEFAULT_COMMENT_SORT: "confidence"
              REDLIB_DEFAULT_SHOW_NSFW: "on"
              REDLIB_DEFAULT_BLUR_NSFW: "on"
              REDLIB_DEFAULT_BLUR_SPOILER: "on"
              REDLIB_DEFAULT_AUTOPLAY_VIDEOS: "off"
              REDLIB_DEFAULT_DISABLE_VISIT_REDDIT_CONFIRMATION: "false"
              REDLIB_ENABLE_RSS: "on"
              REDLIB_FULL_URL: "https://{{ .Release.Name }}.${SECRET_DOMAIN}"
            envFrom:
              - secretRef:
                  name: redlib-secret

            securityContext: &sc
              readOnlyRootFilesystem: true
              allowPrivilegeEscalation: false
              capabilities:
                drop: ["ALL"]

            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /settings
                    port: &port 8080
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
              startup:
                enabled: false

            resources:
              requests:
                cpu: 50m
                memory: 256Mi
              limits:
                memory: 2Gi

    service:
      app:
        controller: *app
        ports:
          http:
            port: *port

    ingress:
      app:
        enabled: true
        className: internal
        annotations:
          gethomepage.dev/enabled: "true"
          gethomepage.dev/name: redlib
          gethomepage.dev/description: reddit frontend
          gethomepage.dev/group: media
          gethomepage.dev/icon: sh-redlib.svg
          gethomepage.dev/pod-selector: >-
            app in (
              redlib
            )
        hosts:
          - host: &host "{{ .Release.Name }}.${SECRET_DOMAIN}"
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
