# yaml-language-server: $schema=https://raw.githubusercontent.com/budimanjojo/talhelper/master/pkg/config/schemas/talconfig.json
---
# renovate: datasource=docker depName=ghcr.io/siderolabs/installer
talosVersion: v1.10.6
# renovate: datasource=docker depName=ghcr.io/siderolabs/kubelet
kubernetesVersion: v1.33.4

clusterName: kubernetes
endpoint: https://10.10.10.20:6443

clusterPodNets:
  - "10.69.0.0/16"
clusterSvcNets:
  - "10.96.0.0/16"

additionalApiServerCertSans: &sans
  - "10.10.10.20"
  - "127.0.0.1"
additionalMachineCertSans: *sans

# Disable built-in Flannel to use Cilium
cniConfig:
  name: none

nodes:
  - hostname: "controller-1"
    ipAddress: "10.10.10.50"
    installDiskSelector:
      serial: "TPBF2411060100303906"
    machineDisks:
      - device: /dev/disk/by-id/nvme-TEAM_TM8FP6001T_TPBF2411060100302920
        partitions:
          - mountpoint: /var/mnt/extra
    machineSpec:
      secureboot: false
    controlPlane: true
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "58:47:ca:7a:b0:3e"
        dhcp: false
        addresses:
          - "10.10.10.50/24"
        routes:
          - network: "10.10.10.0/24"
            gateway: "10.10.10.1"
        mtu: 1500
        vip:
          ip: "10.10.10.20"
      - interface: bond0
        bond:
          mode: active-backup
          deviceSelectors:
            - permanentAddr: "58:47:ca:7a:b0:3f"
        dhcp: true
        vlans:
          - &vlan2
            vlanId: 2
            mtu: 1500
            dhcpOptions:
              routeMetric: 4096
          - &vlan25
            vlanId: 25
            mtu: 1500
            dhcpOptions:
              routeMetric: 4096

  - hostname: "controller-2"
    ipAddress: "10.10.10.51"
    installDiskSelector:
      serial: "TPBF2411060100302903"
    machineDisks:
      - device: /dev/disk/by-id/nvme-TEAM_TM8FP6001T_TPBF2411060100303393_1
        partitions:
          - mountpoint: /var/mnt/extra
    machineSpec:
      secureboot: false
    controlPlane: true
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "58:47:ca:7a:ac:7e"
        dhcp: false
        addresses:
          - "10.10.10.51/24"
        routes:
          - network: "10.10.10.0/24"
            gateway: "10.10.10.1"
        mtu: 1500
        vip:
          ip: "10.10.10.20"
      - interface: bond0
        bond:
          mode: active-backup
          deviceSelectors:
            - permanentAddr: "58:47:ca:7a:ac:7f"
        dhcp: true
        vlans:
          - *vlan2
          - *vlan25

  - hostname: "controller-3"
    ipAddress: "10.10.10.52"
    installDiskSelector:
      serial: "TPBF2411060100302774"
    machineDisks:
      - device: /dev/disk/by-id/nvme-TEAM_TM8FP6001T_TPBF2411060100302759
        partitions:
          - mountpoint: /var/mnt/extra
    machineSpec:
      secureboot: false
    controlPlane: true
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "58:47:ca:7a:c5:ea"
        dhcp: false
        addresses:
          - "10.10.10.52/24"
        routes:
          - network: "10.10.10.0/24"
            gateway: "10.10.10.1"
        mtu: 1500
        vip:
          ip: "10.10.10.20"
      - interface: bond0
        bond:
          mode: active-backup
          deviceSelectors:
            - permanentAddr: "58:47:ca:7a:c5:eb"
        dhcp: true
        vlans:
          - *vlan2
          - *vlan25

# Global patches
patches:
  - "@./patches/global/machine-features.yaml"
  - "@./patches/global/machine-files.yaml"
  - "@./patches/global/machine-kernel.yaml"
  - "@./patches/global/machine-kubelet.yaml"
  - "@./patches/global/machine-network.yaml"
  - "@./patches/global/machine-sysctls.yaml"
  - "@./patches/global/machine-sysfs.yaml"
  - "@./patches/global/machine-time.yaml"
  - "@./patches/global/machine-udev.yaml"

# Controller patches
controlPlane:
  patches:
    - "@./patches/controller/admission-controller-patch.yaml"
    - "@./patches/controller/cluster.yaml"

  schematic:
    customization:
      extraKernelArgs:
        - apparmor=0 # Less security, faster puter
        - init_on_alloc=0 # Less security, faster puter
        - init_on_free=0 # Less security, faster puter
        - intel_iommu=on # PCI Passthrough
        - iommu=pt # PCI Passthrough
        - mitigations=off # Less security, faster puter
        - security=none # Less security, faster puter
        - talos.auditd.disabled=1 # Less security, faster puter

      systemExtensions:
        officialExtensions:
          - siderolabs/gasket-driver
          - siderolabs/i915
          - siderolabs/intel-ucode
          - siderolabs/mei
          - siderolabs/thunderbolt
