---
# yaml-language-server: $schema=https://kube-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app paperless
  namespace: &namespace media
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  components:
    - ../../../../flux/components/gatus/guarded
    - ../../../../flux/components/volsync
  dependsOn:
    - name: crunchy-postgres-cluster
      namespace: storage
    - name: dragonfly-cluster
      namespace: storage
    - name: onepassword-store
      namespace: security
    - name: volsync
      namespace: storage
  interval: 30m
  path: ./kubernetes/apps/media/paperless/app
  postBuild:
    substitute:
      APP: *app
      VOLSYNC_CAPACITY: 15Gi
      APP_UID: "1003"
      APP_GID: "100"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: *namespace
  timeout: 5m
  wait: false
