---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app shlink-api
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 3.7.2
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      shlink-api:
        replicas: 1
        annotations:
          secret.reloader.stakater.com/reload: &secret shlink-secret
        pod:
          topologySpreadConstraints:
            - maxSkew: 1
              topologyKey: kubernetes.io/hostname
              whenUnsatisfiable: DoNotSchedule
              labelSelector:
                matchLabels:
                  app.kubernetes.io/name: *app
        containers:
          app:
            image:
              repository: ghcr.io/shlinkio/shlink
              tag: 4.4.5@sha256:83b1108bb0bee3a59768111b3a3a0e7c90abec61bb356acebd7dc9221d1ab272
            env:
              DB_DRIVER: postgres
              DEFAULT_DOMAIN: &host "ln.${SECRET_HOME_DOMAIN}"
              DISABLE_TRACKING_FROM: 10.0.0.0/8,172.16.0.0/12,192.168.0.0/16
              ENABLE_PERIODIC_VISIT_LOCATE: "true"
              IS_HTTPS_ENABLED: "true"
              PORT: &port 8080
              TIMEZONE: "${TIMEZONE}"
            envFrom:
              - secretRef:
                  name: *secret
    service:
      app:
        controller: *app
        ports:
          http:
            port: *port
    ingress:
      app:
        enabled: true
        className: external-home
        hosts:
          - host: *host
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
      home:
        enabled: true
        className: external
        hosts:
          - host: "ln.${SECRET_DOMAIN}"
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
