---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: kosync
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: kosync-secret
    template:
      engineVersion: v2
      data:
        DB_NAME: '{{ index . "dbname" }}'
        DB_HOST: '{{ index . "pgbouncer-host" }}'
        DB_USER: '{{ index . "user" }}'
        DB_PASS: '{{ index . "password" }}'
        DB_PORT: '{{ index . "pgbouncer-port" }}'
        AUTH_SALT: '{{ .KSYN_AUTH_SALT }}'
        STORAGE_DSN: 'host={{ index . "pgbouncer-host" }} user={{ index . "user" }} password={{ index . "password" }} dbname={{ index . "dbname" }} port={{ index . "pgbouncer-port" }} sslmode=disable'
  dataFrom:
    - extract:
        key: kosync
      sourceRef:
        storeRef:
          kind: ClusterSecretStore
          name: onepassword
    - extract:
        key: crunchy-postgres-pguser-kosync
      sourceRef:
        storeRef:
          kind: ClusterSecretStore
          name: crunchy-postgres
