---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app kosync
spec:
  interval: 15m
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      kosync:
        strategy: RollingUpdate
        annotations:
          reloader.stakater.com/auto: "true"

        containers:
          app:
            image:
              repository: ghcr.io/usa-reddragon/kosync
              tag: v0.0.16
              pullPolicy: IfNotPresent

            env:
              STORAGE_TYPE: "postgres"
              METRICS_ENABLED: "true"
              LOG_LEVEL: "debug"

            envFrom:
              - secretRef:
                  name: kosync-secret

    service:
      app:
        controller: *app
        ports:
          http:
            port: 8080
          metrics:
            port: 9000
          pprof:
            port: 9999

    ingress:
      app:
        className: internal
        hosts:
          - host: &host kosync.${SECRET_DOMAIN}
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
