---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: unpackerr
spec:
  target:
    name: unpackerr-secret
    template:
      data:
        UN_RADARR_0_API_KEY: "{{ .RADARR_API_KEY }}"
        UN_SONARR_0_API_KEY: "{{ .SONARR_API_KEY }}"
  dataFrom:
    - extract:
        key: radarr
      sourceRef:
        storeRef:
          kind: ClusterSecretStore
          name: onepassword
    - extract:
        key: sonarr
      sourceRef:
        storeRef:
          kind: ClusterSecretStore
          name: onepassword
