---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: homebox
spec:
  refreshInterval: 5m
  target:
    name: homebox-secret
    creationPolicy: Owner
    template:
      data:
        HBOX_MAILER_HOST: "{{ .EXTERNAL_SMTP_HOST }}"
        HBOX_MAILER_PORT: "{{ .EXTERNAL_SMTP_PORT }}"
        HBOX_MAILER_USERNAME: "{{ .EXTERNAL_SMTP_USER }}"
        HBOX_MAILER_PASSWORD: "{{ .EXTERNAL_SMTP_PASS }}"
        HBOX_MAILER_FROM: "{{ .EXTERNAL_SMTP_FROM_EMAIL }}"
  dataFrom:
    - extract:
        key: n8n
      sourceRef:
        storeRef:
          kind: ClusterSecretStore
          name: onepassword
    - extract:
        key: external-smtp
      sourceRef:
        storeRef:
          kind: ClusterSecretStore
          name: onepassword
