---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app homebox
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.7.2
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 2
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      homebox:
        containers:
          app:
            image:
              repository: ghcr.io/sysadminsmedia/homebox
              tag: 0.18.0@sha256:1a2239e49c4a4e05e21687fd456b601c77f366200f3ab99321080dc871171b6c
            env:
              TZ: "${TIMEZONE}"
              HBOX_LOG_LEVEL: info
              HBOX_LOG_FORMAT: text
              HBOX_MEB_MAX_UPLOAD_SIZE: 10
              HBOX_OPTIONS_CHECK_GITHUB_RELEASE: false
              HBOX_DATABASE_DRIVER: postgres
            envFrom:
              - secretRef:
                  name: homebox-secret
            resources:
              requests:
                cpu: 100m
                memory: 64M
              limits:
                memory: 256M

    service:
      app:
        controller: *app
        ports:
          http:
            port: 7745
    ingress:
      app:
        enabled: true
        className: internal
        annotations:
          gethomepage.dev/enabled: "true"
          gethomepage.dev/name: homebox
          gethomepage.dev/description: home inventory
          gethomepage.dev/group: apps
          gethomepage.dev/icon: sh-homebox.svg
          gethomepage.dev/pod-selector: >-
            app in (
              homebox
            )
          gethomepage.dev/widget.type: homebox
          gethomepage.dev/widget.url: http://homebox.selfhosted:7745
          gethomepage.dev/widget.username: "{{ `{{HOMEPAGE_VAR_SVC_HBX_USER}}` }}"
          gethomepage.dev/widget.password: "{{ `{{HOMEPAGE_VAR_SVC_HBX_PASS}}` }}"
        hosts:
          - host: &host "{{ .Release.Name }}.${SECRET_DOMAIN}"
            paths:
              - path: /
                service:
                  identifier: app
                  port: http

    persistence:
      data:
        enabled: true
        existingClaim: *app
        globalMounts:
          - path: /data
