---
# yaml-language-server: $schema=https://kube-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: &name immich
  namespace: media
spec:
  target:
    name: immich-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        REDIS_DBINDEX: "{{ .DF_REDIS_IMMICH_DB }}"

        JWT_SECRET: "{{ .IMMICH_JWT_SECRET }}"

        DB_HOSTNAME: '{{ index . "host" }}'
        DB_PORT: '{{ index . "port" }}'
        DB_USERNAME: '{{ index . "user" }}'
        DB_PASSWORD: '{{ index . "password" }}'
        DB_DATABASE_NAME: '{{ index . "dbname" }}'
  dataFrom:
    - sourceRef:
        secretStoreRef:
          kind: ClusterSecretStore
          name: onepassword
      extract:
        key: immich
    - sourceRef:
        secretStoreRef:
          kind: ClusterSecretStore
          name: onepassword
      extract:
        key: dragonfly
    - sourceRef:
        secretStoreRef:
          kind: ClusterSecretStore
          name: crunchy-postgres
      extract:
        key: crunchy-postgres-vector-pguser-immich
