---
# yaml-language-server: $schema=https://kube-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: &name immich
  namespace: media
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: immich-secret
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      engineVersion: v2
      data:
        REDIS_DBINDEX: "{{ .DF_REDIS_IMMICH_DB }}"

        JWT_SECRET: "{{ .IMMICH_JWT_SECRET }}"
  dataFrom:
    - extract:
        key: immich
    - extract:
        key: dragonfly

---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: immich-db
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: crunchy-pgo-secrets
  target:
    name: immich-secret
    creationPolicy: Merge
    deletionPolicy: Retain
    template:
      engineVersion: v2
      data:
        DB_HOSTNAME: '{{ index . "host" }}'
        DB_PORT: '{{ index . "port" }}'
        DB_USERNAME: '{{ index . "user" }}'
        DB_PASSWORD: '{{ index . "password" }}'
        DB_DATABASE_NAME: '{{ index . "dbname" }}'
  dataFrom:
    - extract:
        key: crunchy-postgres-vector-pguser-immich
