---
# yaml-language-server: $schema=https://kube-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: &name immich
  namespace: media
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: immich-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        # Immich
        DB_DATABASE_NAME: &dbname "{{ .IMMICH_PG_DB }}"
        DB_HOSTNAME: &dbhost "{{ .PGIMMICH_RW_INTERNAL_HOST }}"
        DB_USERNAME: &dbuser "{{ .IMMICH_PG_USER }}"
        DB_PASSWORD: &dbpass "{{ .IMMICH_PG_PASS }}"

        REDIS_DBINDEX: "{{ .DF_REDIS_IMMICH_DB }}"

        JWT_SECRET: "{{ .IMMICH_JWT_SECRET }}"

        # Postgres Init
        INIT_POSTGRES_DBNAME: *dbname
        INIT_POSTGRES_HOST: *dbhost
        INIT_POSTGRES_USER: *dbuser
        INIT_POSTGRES_PASS: *dbpass
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
  dataFrom:
    - extract:
        key: immich
    - extract:
        key: cloudnative-pg
    - extract:
        key: dragonfly
