---
# Area
- name: area/templates
  color: "0e8a16"

- name: area/github
  color: "0e8a16"

- name: area/kubernetes
  color: "0e8a16"

- name: area/taskfile
  color: "0e8a16"

# Renovate
- name: renovate/container
  color: "027fa0"

- name: renovate/github- action
  color: "027fa0"

- name: renovate/github- release
  color: "027fa0"

- name: renovate/helm
  color: "027fa0"

# SemanticType
- name: type/patch
  color: "ffec19"

- name: type/minor
  color: "ff9800"

- name: type/major
  color: "f6412d"

- name: type/break
  color: "f6412d"

# issues

- name: bug
  color: "e11d21"

- name: feat
  color: "009800"
  aliases:
    - "enhancement"
    - "feature"

- name: question
  color: "cc317c"
  aliases:
    - "discussion"

- name: doc
  color: "207de5"
  aliases:
    - "documentation"

- name: prio/low
  color: "009800"

- name: prio/med
  color: "fbca04"

- name: prio/high
  color: "eb6420"

- name: prio/critical
  color: "e11d21"

- name: status/starter
  color: "bfe5bf"
  aliases:
    - "beginner"
    - "good-starter-issue"

- name: status/blocked
  color: "990000"

# Uncategorized
- name: hold
  color: "ee0701"
