---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: invidious
spec:
  target:
    name: invidious-secret
    template:
      engineVersion: v2
      data:
        INVIDIOUS_CONFIG: |
          db:
            dbname: "{{ .dbname }}"
            host: '{{ index . "pgbouncer-host" }}'
            port: '{{ index . "pgbouncer-port" }}'
            user: '{{ .user }}'
            password: "{{ .password }}"
          check_tables: true
          domain: invidious.${SECRET_DOMAIN}
          external_port: 443
          https_only: true
          hmac_key: {{ .INVID_HMAC_KEY }}
          admins: ["ben-admin"]
          channel_threads: 2
          full_refresh: false
          signature_server: localhost:12999
          po_token: "{{ .token }}=="
          visitor_data: "{{ .visitor }}"
  dataFrom:
    - extract:
        key: invidious
      sourceRef:
        storeRef:
          kind: ClusterSecretStore
          name: onepassword
    - extract:
        key: crunchy-postgres-pguser-invidious
      sourceRef:
        storeRef:
          kind: ClusterSecretStore
          name: crunchy-postgres
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: Password
          name: invid-token
      rewrite: # https://github.com/external-secrets/external-secrets/issues/3823
        - regexp:
            source: "password"
            target: "token"
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: Password
          name: invid-visitor
      rewrite:
        - regexp:
            source: "password"
            target: "visitor"
