---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/common-3.0.1/charts/library/common/values.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app invidious
spec:
  interval: 15m
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      invidious:
        strategy: RollingUpdate
        annotations:
          reloader.stakater.com/auto: "true"

        containers:
          app:
            image:
              repository: quay.io/invidious/invidious
              tag: latest@sha256:c9b87b8e33484f0a2fd5fc9b386ddbad81b704b3361e45881b3821295ceabd6d

            env:
              TZ: "${TIMEZONE}"
              INVIDIOUS_PORT: "3000"
              INVIDIOUS_SIGNATURE_SERVER: inv-sig-helper.media.svc.cluster.local:12999

            envFrom: &envFrom
              - secretRef:
                  name: invidious-secret

            resources:
              requests:
                cpu: 50m
                memory: 256Mi

    service:
      app:
        controller: *app
        ports:
          http:
            port: 3000

    ingress:
      app:
        enabled: true
        className: internal
        annotations:
          nginx.ingress.kubernetes.io/whitelist-source-range: "10.0.0.0/8, 172.16.0.0/12, 192.168.0.0/16, 100.90.0.0/10"
          gethomepage.dev/enabled: "true"
          gethomepage.dev/group: media
          gethomepage.dev/name: invidious
          gethomepage.dev/icon: sh-invidious.svg
          gethomepage.dev/description: yt frontend
        hosts:
          - host: &host "{{ .Release.Name }}.${SECRET_DOMAIN}"
            paths:
              - path: /
                service:
                  identifier: app
                  port: http

      tailscale:
        className: tailscale
        hosts:
          - host: &tshost "{{ .Release.Name }}.${SECRET_TS_DOMAIN}"
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
        tls:
          - hosts:
              - *tshost
