---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/common-3.0.1/charts/library/common/values.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app invidious
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 3.7.2
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 15m
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      invidious:
        strategy: RollingUpdate
        annotations:
          reloader.stakater.com/auto: "true"

        initContainers:
          inv-sig-helper:
            image:
              repository: quay.io/invidious/inv-sig-helper
              tag: latest
              pullPolicy: IfNotPresent
            command: ["/app/inv_sig_helper_rust", "--tcp", "0.0.0.0:12999"]
            env:
              RUST_LOG: debug
              RUST_BACKTRACE: full
            restartPolicy: Always
            securityContext:
              capabilities:
                drop:
                  - ALL

        containers:
          app:
            image:
              repository: quay.io/invidious/invidious
              tag: latest@sha256:6ff95432b1e3b0f21592d581dbe1589c8d8ad2a6dc2792e17cdb102308e438e6

            envFrom: &envFrom
              - secretRef:
                  name: invidious-secret

            resources:
              requests:
                cpu: 50m
                memory: 256Mi

    service:
      app:
        controller: *app
        ports:
          http:
            port: 3000

    ingress:
      app:
        enabled: true
        className: internal
        annotations:
          nginx.ingress.kubernetes.io/whitelist-source-range: "10.0.0.0/8, 172.16.0.0/12, 192.168.0.0/16, 100.90.0.0/10"
          gethomepage.dev/enabled: "true"
          gethomepage.dev/group: media
          gethomepage.dev/name: invidious
          gethomepage.dev/icon: sh-invidious.svg
          gethomepage.dev/description: yt frontend
        hosts:
          - host: &host "{{ .Release.Name }}.${SECRET_DOMAIN}"
            paths:
              - path: /
                service:
                  identifier: app
                  port: http

      tailscale:
        className: tailscale
        hosts:
          - host: &tshost "{{ .Release.Name }}.${SECRET_TS_DOMAIN}"
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
        tls:
          - hosts:
              - *tshost
