---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app atuin
  namespace: &namespace default
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  dependsOn:
    - name: onepassword-store
      namespace: security
  components:
    - ../../../../flux/components/gatus/guarded
    # - ../../../../flux/components/volsync
  interval: 30m
  path: ./kubernetes/apps/default/atuin/app
  postBuild:
    substitute:
      APP: *app
      GATUS_SUBDOMAIN: sh
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: *namespace
  timeout: 5m
  wait: false
