---
# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"

tasks:
  gen-32:
    desc: Generate rand hex 32
    cmds:
      - openssl rand -hex 32

  gen-64:
    desc: Generate rand hex 64
    cmds:
      - openssl rand -hex 64

  gen-pair:
    desc: Generate oidc/ oauth pairs
    cmds:
      - echo "Client ID"
      - openssl rand -hex 32
      - echo "Client Secret:"
      - openssl rand -hex 64
