---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflared
spec:
  target:
    name: cloudflared-secret
    template:
      engineVersion: v2
      data:
        config.yaml: |
          tunnel: "{{ .CFD_KNETES_TUNNEL_ID }}"

          ingress:
            - hostname: "{{ .CF_DOMAIN_KNETES }}"
              service: https://external-ingress-nginx-controller.network.svc.cluster.local:443
              originRequest:
                originServerName: external.{{ .CF_DOMAIN_KNETES }}

            - hostname: "{{ .CF_DOMAIN_KNETES_WC }}"
              service: https://external-ingress-nginx-controller.network.svc.cluster.local:443
              originRequest:
                originServerName: external.{{ .CF_DOMAIN_KNETES }}

            - hostname: "{{ .CF_DOMAIN_HOME }}"
              service: https://external-ingress-nginx-home-controller.network.svc.cluster.local:443
              originRequest:
                originServerName: external.{{ .CF_DOMAIN_HOME }}

            - hostname: "{{ .CF_DOMAIN_HOME_WC }}"
              service: https://external-ingress-nginx-home-controller.network.svc.cluster.local:443
              originRequest:
                originServerName: external.{{ .CF_DOMAIN_HOME }}

            - service: http_status:404
        credentials.json: |
          {
            "AccountTag": "{{ .CF_ACCOUNT_ID }}",
            "TunnelSecret": "{{ .CFD_KNETES_TUNNEL_SECRET }}",
            "TunnelID": "{{ .CFD_KNETES_TUNNEL_ID }}"
          }
  dataFrom:
    - extract:
        key: cloudflare
      sourceRef:
        storeRef:
          kind: ClusterSecretStore
          name: onepassword
