---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: media
components:
  - ../../components/common
resources:
  - ./bazarr/ks.yaml
  - ./calibre-web/ks.yaml
  - ./flaresolverr/ks.yaml
  - ./immich/ks.yaml
  - ./invidious/ks.yaml
  - ./lidarr/ks.yaml
  - ./overseerr/ks.yaml
  - ./paperless/ks.yaml
  - ./pinchflat/ks.yaml
  - ./prowlarr/ks.yaml
  - ./radarr/ks.yaml
  - ./readarr-books/ks.yaml
  - ./recyclarr/ks.yaml
  - ./redlib/ks.yaml
  - ./sabnzbd/ks.yaml
  - ./sonarr/ks.yaml
  - ./theme-park/ks.yaml
  - ./unpackerr/ks.yaml
