---
commitizen:
  name: cz_gitmoji
  version_provider: "commitizen"
  version_files:
    - src/__version__.py
    - pyproject.toml:version
  update_changelog_on_bump: true
  major_version_zero: true
  version: 0.0.1
