[env]
# Python environment
_.python.venv = { path = "{{config_root}}/.venv", create = true }

# Kubernetes related
KUBERNETES_DIR = '{{config_root}}/kubernetes'
KUBECONFIG = "{{config_root}}/kubeconfig"

# Configuration files
MINIJINJA_CONFIG_FILE = '{{config_root}}/.config/.minijinja.toml'
SOPS_AGE_KEY_FILE = "{{config_root}}/age.key"
TALOSCONFIG = "{{config_root}}/infrastructure/talos/clusterconfig/talosconfig"

[tasks.deps]
description = "Install dependencies"
run = "uv pip install -r .config/requirements.txt"

[tasks.clean]
description = "Clean up temporary files and caches"
run = "rm -rf .pytest_cache __pycache__ .coverage .mypy_cache"

[tasks.lint]
description = "Run all linters"
run = "pre-commit run --all-files"

[tasks.format]
description = "Format code"
run = "pre-commit run --all-files black isort"

[tools]
# Template tools
python = "3.13"
uv = "latest"
age = "latest"
sops = "latest"

# Operations tools
"aqua:budimanjojo/talhelper" = "3.0.30"
"aqua:cloudflare/cloudflared" = "2025.6.1"
"aqua:FiloSottile/age" = "1.2.1"
"aqua:fluxcd/flux2" = "2.6.3"
"aqua:getsops/sops" = "3.10.2"
"aqua:go-task/task" = "3.44.0"
"aqua:helm/helm" = "3.18.3"
"aqua:helmfile/helmfile" = "1.1.2"
"aqua:jqlang/jq" = "1.7.1"
"aqua:kubernetes-sigs/kustomize" = "5.6.0"
"aqua:kubernetes/kubectl" = "1.32.1"
"aqua:mikefarah/yq" = "4.45.4"
"aqua:siderolabs/talos" = "1.10.4"
"aqua:yannh/kubeconform" = "0.7.0"
"aqua:pre-commit/pre-commit" = "latest"
"pipx:cz-conventional-gitmoji" = "latest"
