repos:
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v4.2.1
    hooks:
      - id: commitizen
        additional_dependencies: [cz-conventional-gitmoji]
      - id: commitizen-branch
        stages: [manual]
  - repo: https://github.com/gitguardian/ggshield
    rev: v1.36.0
    hooks:
      - id: ggshield
        language_version: python3
        stages: [pre-commit]
