---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app rook-ceph-haproxy
  namespace: flux-system
spec:
  targetNamespace: rook-ceph-external
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  path: ./kubernetes/talos-maxi/apps/rook-ceph-external/rook-ceph/haproxy/app
  prune: false
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
