---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: external-external-dns
spec:
  target:
    name: external-external-dns-secret
    template:
      data:
        CF_API_TOKEN: "{{ .CF_API_TOKEN }}"
  dataFrom:
    - extract:
        key: cloudflare
      sourceRef:
        storeRef:
          kind: ClusterSecretStore
          name: onepassword
