---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app cloudnative-pg
  namespace: flux-system
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  dependsOn:
    - name: onepassword-store
  interval: 30m
  path: ./kubernetes/apps/storage/cloudnative-pg/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  targetNamespace: storage
  timeout: 5m
  wait: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app cloudnative-pg-cluster
  namespace: flux-system
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  dependsOn:
    - name: cloudnative-pg
    - name: openebs
  interval: 30m
  path: ./kubernetes/apps/storage/cloudnative-pg/cluster
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  targetNamespace: storage
  timeout: 5m
  wait: true
