---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app immich-machine-learning
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.7.1
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  dependsOn:
    - name: immich-server
      namespace: media
    - name: dragonfly-operator
      namespace: storage

  maxHistory: 2
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false

  values:
    defaultPodOptions:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        supplementalGroups:
          - 100
        fsGroupChangePolicy: OnRootMismatch

      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchLabels:
              app.kubernetes.io/name: *app

    controllers:
      immich-machine-learning:
        annotations:
          configmap.reloader.stakater.com/reload: &configMap immich-configmap
          secret.reloader.stakater.com/reload: &secret immich

        containers:
          app:
            image:
              repository: ghcr.io/immich-app/immich-machine-learning
              tag: v1.126.1

            envFrom:
              - configMapRef:
                  name: *configMap
              - secretRef:
                  name: *secret

            env:
              # General
              IMMICH_MEDIA_LOCATION: &mediaLocation /usr/src/app/upload
              # Ports
              MACHINE_LEARNING_HOST: 0.0.0.0
              MACHINE_LEARNING_PORT: &port 3003

            resources:
              requests:
                cpu: 100m
                memory: 274M
              limits:
                memory: 3949M

    service:
      app:
        controller: *app
        ports:
          http:
            port: *port

    persistence:
      library:
        enabled: true
        existingClaim: immich-nfs
        globalMounts:
          - path: /usr/src/app/upload
            subPath: img/immich

      cache:
        type: persistentVolumeClaim
        existingClaim: immich-machine-learning-cache
        globalMounts:
          - path: /cache

      geocoding-dump:
        enabled: true
        type: emptyDir
        globalMounts:
          - path: /usr/src/app/.reverse-geocoding-dump

      transformers-cache:
        enabled: true
        type: emptyDir
        globalMounts:
          - path: /usr/src/app/.transformers_cache
