---
apiVersion: v1
kind: Service
metadata:
  name: homeassistant
  namespace: network
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8123
---
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: homeassistant
  namespace: network
  labels:
    kubernetes.io/service-name: homeassistant
addressType: IPv4
ports:
  - name: http
    appProtocol: http
    protocol: TCP
    port: 8123
endpoints:
  - addresses:
      - "10.20.13.20"
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: &app homeassistant
  namespace: network
  labels:
    app.kubernetes.io/name: *app
    app.kubernetes.io/instance: *app
  annotations:
    gethomepage.dev/enabled: "true"
    gethomepage.dev/icon: sh-homeassistant.svg
    gethomepage.dev/name: homeassistant
    gethomepage.dev/group: iot
spec:
  ingressClassName: internal
  rules:
    - host: hass.${SECRET_DOMAIN}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: *app
                port:
                  number: 8123
