---
apiVersion: v1
kind: Service
metadata:
  name: unraid
  namespace: network
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: unraid
  namespace: network
  labels:
    kubernetes.io/service-name: unraid
addressType: IPv4
ports:
  - name: http
    appProtocol: http
    protocol: TCP
    port: 80
endpoints:
  - addresses:
      - "10.20.13.10"
---
apiVersion: network.k8s.io/v1
kind: Ingress
metadata:
  name: &app unraid
  namespace: network
  labels:
    app.kubernetes.io/name: *app
    app.kubernetes.io/instance: *app
  annotations:
    gethomepage.dev/enabled: "true"
    gethomepage.dev/icon: sh-unraid.svg
    gethomepage.dev/name: unraid
    gethomepage.dev/group: infra
spec:
  ingressClassName: internal
  rules:
    - host: tower.${SECRET_DOMAIN}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: *app
                port:
                  number: 80
