---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: hajimari
spec:
  interval: 30m
  chart:
    spec:
      chart: hajimari
      version: 2.0.2
      sourceRef:
        kind: HelmRepository
        name: hajimari
        namespace: flux-system
  maxHistory: 2
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controller:
      strategy: RollingUpdate
    podAnnotations:
      configmap.reloader.stakater.com/reload: hajimari-settings
    env:
      TZ: ${TIMEZONE}
    hajimari:
      title: Apps
      lightTheme: tron
      darkTheme: tron
      alwaysTargetBlank: true
      showSearch: false
      showGreeting: false
      showAppGroups: false
      showAppStatus: false
      showBookmarkGroups: false
      showGlobalBookmarks: false
      showAppUrls: false
      defaultEnable: true
      namespaceSelector:
        matchNames:
          - default
          - flux-system
          - iot
          - network
          - observability
          - rook-ceph
          - storage
      customApps:
        - group: servers
          apps:
            - name: unraid
              icon: mdi:nas
              url: "http://tower.${INTERNAL_DOMAIN}"
            - name: pikvm
              icon: mdi:ip-network
              url: "https://pikvm.${INTERNAL_DOMAIN}"
      bookmarks:
        - group: Kubernetes
          bookmarks:
            - name: benwalio/opstimus-prime
              icon: ""
              url: "${GHUB_HTTP_URL}"
              targetBlank: false
            - name: k8s-at-home-search
              icon: ""
              url: https://whazor.github.io/k8s-at-home-search/
              targetBlank: false
    ingress:
      app:
        enabled: true
        ingressClassName: internal
        annotations:
          hajimari.io/enable: "false"
          hajimari.io/icon: weather-sunset
          hajimari.io/instance: admin
        hosts:
          - host: &host apps.${SECRET_EXTERNAL_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
    persistence:
      data:
        enabled: true
        type: emptyDir
    resources:
      requests:
        cpu: 100m
        memory: 128M
