---
# yaml-language-server: $schema=https://kube-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name cloudnative-pg-operator
spec:
  target:
    name: cloudnative-pg-operator-secret
    template:
      engineVersion: v2
      data:
        username: "{{ .POSTGRES_SUPER_USER }}"
        password: "{{ .POSTGRES_SUPER_PASS }}"
        POSTGRES_SUPER_USER: "{{ .POSTGRES_SUPER_USER }}"
        POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
  dataFrom:
    - extract:
        key: cloudnative-pg
      sourceRef:
        storeRef:
          kind: ClusterSecretStore
          name: onepassword
