---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: iot
components:
  - ../../flux/components/common
resources:
  - ./emqx/ks.yaml
