---
# yaml-language-server: $schema=https://kube-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: paperless-ai
spec:
  target:
    name: paperless-ai-secret
    template:
      data:
        # App
        PAPERLESS_API_TOKEN: "{{ .PPRL_2_HP_SECRET }}"

  dataFrom:
    - extract:
        key: paperless
      sourceRef:
        storeRef:
          kind: ClusterSecretStore
          name: onepassword
