---
# yaml-language-server: $schema=https://kube-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: paperless
spec:
  target:
    name: paperless-secret
    template:
      data:
        # App
        PAPERLESS_ADMIN_USER: "{{ .PPRL_ADMIN_USER }}"
        PAPERLESS_ADMIN_PASSWORD: "{{ .PPRL_ADMIN_PASS }}"
        PAPERLESS_SECRET_KEY: "{{ .PPRL_SECRET_KEY }}"
        PAPERLESS_SOCIALACCOUNT_PROVIDERS: |-
          {
            "openid_connect": {
                "APPS": [
                    {
                        "provider_id": "authentik",
                        "name": "Authentik",
                        "client_id": "{{ .PPRL_AK_CLIENT_ID }}",
                        "secret": "{{ .PPRL_AK_CLIENT_SECRET }}",
                        "settings": {
                            "server_url": "https://sso.${SECRET_DOMAIN}/application/o/paperless/.well-known/openid-configuration"
                        }
                    }
                ]
            }
          }
        # Database
        PAPERLESS_DBENGINE: postgresql
        PAPERLESS_DBHOST: '{{ index . "host" }}'
        PAPERLESS_DBPORT: '{{ index . "port" }}'
        PAPERLESS_DBNAME: '{{ index . "dbname" }}'
        PAPERLESS_DBUSER: '{{ index . "user" }}'
        PAPERLESS_DBPASS: '{{ index . "password" }}'
        # user
        USERMAP_UID: "{{ .PPRL_UID }}"
        USERMAP_GID: "{{ .PPRL_GID }}"

  dataFrom:
    - extract:
        key: paperless
      sourceRef:
        storeRef:
          kind: ClusterSecretStore
          name: onepassword
    - extract:
        key: crunchy-postgres-pguser-paperless
      sourceRef:
        storeRef:
          kind: ClusterSecretStore
          name: crunchy-postgres
