# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app paperless
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.7.3
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  dependsOn:
    - name: rook-ceph-cluster
      namespace: rook-ceph
    - name: volsync
      namespace: storage
  values:
    defaultPodOptions:
      securityContext:
        runAsUser: 1003
        runAsGroup: 100

    controllers:
      paperless:
        labels:
          nfsMount: "true"
          postgres: "true"
        annotations:
          reloader.stakater.com/auto: "true"
        pod:
          securityContext:
            supplementalGroups:
              - 65542
        containers:
          app:
            image:
              repository: ghcr.io/paperless-ngx/paperless-ngx
              tag: 2.15.0
            env:
              # Configure application
              PAPERLESS_APPS: allauth.socialaccount.providers.openid_connect
              PAPERLESS_REDIS_PREFIX: pngx
              PAPERLESS_URL: https://docs.${SECRET_DOMAIN}
              PAPERLESS_PORT: "8000"
              PAPERLESS_TIME_ZONE: ${TIMEZONE}
              PAPERLESS_WEBSERVER_WORKERS: "2"
              PAPERLESS_TASK_WORKERS: "2"
              # Configure Remote User auth
              PAPERLESS_ACCOUNT_ALLOW_SIGNUPS: "false"
              PAPERLESS_SOCIALACCOUNT_ALLOW_SIGNUPS: "true"
              # Configure folders
              PAPERLESS_CONSUMPTION_DIR: /data/consume/paperless
              PAPERLESS_DATA_DIR: /data/local/data
              PAPERLESS_EXPORT_DIR: /data/local/export
              PAPERLESS_MEDIA_ROOT: /data/nas/docs/paperless
              # Configure folder importer
              PAPERLESS_CONSUMER_POLLING: "60"
              PAPERLESS_CONSUMER_RECURSIVE: "true"
              PAPERLESS_CONSUMER_SUBDIRS_AS_TAGS: "true"
              # Configure OCR
              PAPERLESS_OCR_LANGUAGES: eng
              PAPERLESS_OCR_LANGUAGE: eng
              # Configure redis integration
              PAPERLESS_REDIS: redis://dragonfly.storage.svc.cluster.local:6379
              # paperless settings
              PAPERLESS_FILENAME_FORMAT: "{correspondent}/{created_year}/{created_year}-{created_month}-{created_day} {title}"
              PAPERLESS_DATE_ORDER: MDY
            envFrom: &envFrom
              - secretRef:
                  name: &secret paperless-secret
            resources:
              requests:
                cpu: 15m
              limits:
                memory: 4G
    service:
      app:
        controller: *app
        ports:
          http:
            port: 8000
    ingress:
      app:
        className: external
        annotations:
          gethomepage.dev/enabled: "true"
          gethomepage.dev/group: document
          gethomepage.dev/name: Paperless rodeo
          gethomepage.dev/icon: paperless.png
          gethomepage.dev/description: Document OCR Software
          gethomepage.dev/widget.type: paperlessngx
          gethomepage.dev/widget.url: http://paperless.media:8000
          gethomepage.dev/widget.key: "{{ `{{HOMEPAGE_VAR_SVC_PPRL_2_PASS}}` }}"
        hosts:
          - host: "docs.${SECRET_DOMAIN}"
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
    persistence:
      config:
        existingClaim: *app
        globalMounts:
          - path: /data/local

      nas:
        type: nfs
        server: ${SECRET_NFS_SERVER}
        path: ${SECRET_NFS_MOUNT_MEDIA}
        globalMounts:
          - path: /data/nas

      consume:
        type: nfs
        server: ${SECRET_NFS_SERVER}
        path: ${SECRET_NFS_MOUNT_MEDIA_SWAP}
        globalMounts:
          - path: /data/consume
