---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: zigbee2mqtt
spec:
  refreshInterval: 5m
  target:
    name: zigbee2mqtt-secret
    creationPolicy: Owner
    template:
      data:
        MQTT_USER_NAME: "{{ .EMQX_USER_NAME }}"
        MQTT_USER_PASS: "{{ .EMQX_USER_PASS }}"

        ZIGBEE_PAN_ID: "{{ .ZBMQTT_PAN_ID }}"
        ZIGBEE_EXT_PAN_ID: "{{ .ZBMQTT_EXT_PAN_ID_ALT }}"
        ZIGBEE_NETWORK_KEY: "{{ .ZBMQTT_NET_KEY }}"
  dataFrom:
    - extract:
        key: emqx
      sourceRef:
        storeRef:
          kind: ClusterSecretStore
          name: onepassword
    - extract:
        key: zigbee2mqtt
      sourceRef:
        storeRef:
          kind: ClusterSecretStore
          name: onepassword
