---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: zigbee2mqtt
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.7.3
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  dependsOn:
    - name: rook-ceph-cluster
      namespace: rook-ceph
  values:
    controllers:
      zigbee2mqtt:
        annotations:
          reloader.stakater.com/auto: "true"

        containers:
          app:
            image:
              repository: ghcr.io/koenkk/zigbee2mqtt
              tag: 2.2.1
            env:
              Z2M_WATCHDOG: default
              ZIGBEE2MQTT_DATA: /data
              ZIGBEE2MQTT_CONFIG_ADVANCED_CHANNEL: 20
              ZIGBEE2MQTT_CONFIG_ADVANCED_EXT_PAN_ID:
                valueFrom:
                  secretKeyRef:
                    name: zigbee2mqtt-secret
                    key: ZIGBEE_EXT_PAN_ID
              ZIGBEE2MQTT_CONFIG_ADVANCED_LAST_SEEN: ISO_8601
              ZIGBEE2MQTT_CONFIG_ADVANCED_LEGACY_API: false
              ZIGBEE2MQTT_CONFIG_ADVANCED_LEGACY_AVAILABILITY_PAYLOAD: false
              ZIGBEE2MQTT_CONFIG_ADVANCED_LOG_LEVEL: info
              ZIGBEE2MQTT_CONFIG_ADVANCED_LOG_OUTPUT: '["console"]'
              ZIGBEE2MQTT_CONFIG_ADVANCED_NETWORK_KEY:
                valueFrom:
                  secretKeyRef:
                    name: zigbee2mqtt-secret
                    key: ZIGBEE_NETWORK_KEY
              ZIGBEE2MQTT_CONFIG_ADVANCED_PAN_ID:
                valueFrom:
                  secretKeyRef:
                    name: zigbee2mqtt-secret
                    key: ZIGBEE_PAN_ID
              ZIGBEE2MQTT_CONFIG_AVAILABILITY_ACTIVE_TIMEOUT: 60
              ZIGBEE2MQTT_CONFIG_AVAILABILITY_PASSIVE_TIMEOUT: 2000
              ZIGBEE2MQTT_CONFIG_DEVICE_OPTIONS_LEGACY: false
              ZIGBEE2MQTT_CONFIG_DEVICE_OPTIONS_RETAIN: true
              ZIGBEE2MQTT_CONFIG_EXPERIMENTAL_NEW_API: true
              ZIGBEE2MQTT_CONFIG_FRONTEND_PORT: 8080
              ZIGBEE2MQTT_CONFIG_FRONTEND_URL: https://zigbee2mqtt.${SECRET_DOMAIN}
              ZIGBEE2MQTT_CONFIG_HOMEASSISTANT_DISCOVERY_TOPIC: homeassistant
              ZIGBEE2MQTT_CONFIG_HOMEASSISTANT_EXPERIMENTAL_EVENT_ENTITIES: true
              ZIGBEE2MQTT_CONFIG_HOMEASSISTANT_LEGACY_ENTITY_ATTRIBUTES: false
              ZIGBEE2MQTT_CONFIG_HOMEASSISTANT_LEGACY_TRIGGERS: false
              ZIGBEE2MQTT_CONFIG_HOMEASSISTANT_STATUS_TOPIC: homeassistant/status
              ZIGBEE2MQTT_CONFIG_MQTT_BASE_TOPIC: zigbee2mqtt
              ZIGBEE2MQTT_CONFIG_MQTT_INCLUDE_DEVICE_INFORMATION: true
              ZIGBEE2MQTT_CONFIG_MQTT_KEEPALIVE: 60
              ZIGBEE2MQTT_CONFIG_MQTT_REJECT_UNAUTHORIZED: true
              ZIGBEE2MQTT_CONFIG_MQTT_SERVER: "mqtt://emqx-listeners.iot.svc.cluster.local:1883"
              ZIGBEE2MQTT_CONFIG_MQTT_VERSION: 5
              ZIGBEE2MQTT_CONFIG_MQTT_USER:
                valueFrom:
                  secretKeyRef:
                    name: zigbee2mqtt-secret
                    key: MQTT_USER_NAME
              ZIGBEE2MQTT_CONFIG_MQTT_PASSWORD:
                valueFrom:
                  secretKeyRef:
                    name: zigbee2mqtt-secret
                    key: MQTT_USER_PASS
              ZIGBEE2MQTT_CONFIG_PERMIT_JOIN: false
              ZIGBEE2MQTT_CONFIG_SERIAL_ADAPTER: zstack
              ZIGBEE2MQTT_CONFIG_SERIAL_PORT: tcp://10.20.110.20:6638
              ZIGBEE2MQTT_CONFIG_SERIAL_BAUDRATE: 115200
              ZIGBEE2MQTT_CONFIG_SERIAL_DISABLE_LED: false
            resources:
              requests:
                cpu: 50m
                memory: 384M
              limits:
                memory: 384M
          code-server:
            image:
              repository: ghcr.io/coder/code-server
              tag: 4.99.3@sha256:e822acb286dca144f1a10ef847bc8f905d92ea79998f4f021802064badcae5fe
            args:
              - --auth
              - none
              - --disable-telemetry
              - --disable-update-check
              - --user-data-dir
              - /data/.code-server
              - --extensions-dir
              - /data/.code-server
              - --port
              - "12321"
              - /data
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 512M

    service:
      app:
        controller: zigbee2mqtt
        ports:
          http:
            primary: true
            port: 8080
          metrics:
            port: 9000
          code-server:
            port: 12321

    ingress:
      app:
        className: internal
        annotations:
          gethomepage.dev/enabled: "true"
          gethomepage.dev/description: Control Zigbee devices
          gethomepage.dev/group: iot
          gethomepage.dev/icon: sh-zigbee2mqtt.svg
          gethomepage.dev/name: zigbee2mqtt
          nginx.ingress.kubernetes.io/rewrite-target: /$1
        hosts:
          - host: "{{ .Release.Name }}.${SECRET_DOMAIN}"
            paths:
              - path: /(.*)
                service:
                  identifier: app
                  port: http
              - path: /code/(.*)
                service:
                  identifier: app
                  port: code-server

    persistence:
      data:
        existingClaim: zigbee2mqtt-data
        advancedMounts:
          zigbee2mqtt:
            app:
              - path: /data
            code-server:
              - path: /data
