machine:
  kubelet:
    extraMounts:
      - destination: /var/mnt/extra
        type: bind
        source: /var/mnt/extra
        options: ["bind", "rshared", "rw"]
    nodeIP:
      validSubnets:
        - 10.10.10.0/24
