machine:
  udev:
    rules:
      # Thunderbolt
      - ACTION=="add", SUBSYSTEM=="thunderbolt", ATTR{authorized}=="0", ATTR{authorized}="1"
      # Intel GPU
      - SUBSYSTEM=="drm", KERNEL=="renderD*", GROUP="44", MODE="0660"
      # Coral Edge TPU
      - SUBSYSTEM=="apex", KERNEL=="apex*", GROUP="44", MODE="0660"
