---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./hr.yaml
configMapGenerator:
  - name: haproxy-config
    files:
      - haproxy.cfg=./config/haproxy.cfg
generatorOptions:
  disableNameSuffixHash: true
