---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &appname hoarder
  namespace: &namespace default
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *appname
  components:
    - ../../../../flux/components/gatus/guarded
    - ../../../../flux/components/volsync
  dependsOn:
    - name: onepassword
      namespace: security
    - name: rook-ceph-cluster
      namespace: rook-ceph
    - name: volsync
      namespace: storage
  interval: 30m
  path: "./kubernetes/apps/default/hoarder/app"
  postBuild:
    substitute:
      APP: *appname
      VOLSYNC_CLAIM: hoarder-data
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: *namespace
  timeout: 5m
  wait: false
