---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: emqx-init-user
spec:
  refreshInterval: 5m
  target:
    name: emqx-init-user-secret
    creationPolicy: Owner
    template:
      data:
        init-user.json: |
          [
            {"user_id": "{{ .X_EMQX_MQTT_USERNAME }}", "password": "{{ .X_EMQX_MQTT_PASSWORD }}", "is_superuser": true},
            {"user_id": "{{ .EMQX_USER_NAME }}", "password": "{{ .EMQX_USER_PASS }}", "is_superuser": false}
          ]
        init-acl: |
          {allow, {user, "{{ .EMQX_USER_NAME  }}"}, all, ["#"]}.
  dataFrom:
    - extract:
        key: emqx
      sourceRef:
        storeRef:
          kind: ClusterSecretStore
          name: onepassword
