---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app esphome
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      esphome:
        pod:
          annotations:
            k8s.v1.cni.cncf.io/networks: |
              [
                {
                  "name":"multus-iot",
                  "namespace": "network"
                }, {
                  "name":"multus-home",
                  "namespace": "network"
                }
              ]

        annotations:
          reloader.stakater.com/auto: "true"

        containers:
          app:
            image:
              repository: ghcr.io/esphome/esphome
              tag: 2025.6.1

            resources:
              requests:
                cpu: 20m
                memory: 64M
              limits:
                memory: 2G

          code-server:
            image:
              repository: ghcr.io/coder/code-server
              tag: 4.100.3@sha256:c5b7ec231b24f26ecee243e8d9f9df57af906d03c9c8238efd893217c9f1f725
            args:
              - --auth
              - none
              - --disable-telemetry
              - --disable-update-check
              - --user-data-dir
              - /config/.code-server
              - --extensions-dir
              - /config/.code-server
              - --port
              - "12321"
              - /config
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 512M

    service:
      app:
        controller: esphome
        ports:
          http:
            port: 6052
          code-server:
            port: 12321

    ingress:
      app:
        className: internal
        annotations:
          gethomepage.dev/enabled: "true"
          gethomepage.dev/description: ESPHome dashboard
          gethomepage.dev/group: iot
          gethomepage.dev/icon: sh-esphome.svg
          gethomepage.dev/name: ESPHome
        hosts:
          - host: &host "{{ .Release.Name }}.${SECRET_DOMAIN}"
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
              # - path: /code/(.*)
              #   service:
              #     identifier: app
              #     port: code-server

    persistence:
      config:
        existingClaim: *app

      esphome-cache:
        type: emptyDir
        globalMounts:
          - path: /config/.esphome

      secrets:
        type: secret
        name: esphome-secret
        globalMounts:
          - path: /config/secrets.yaml
            subPath: secrets.yaml

      deploy-key:
        type: secret
        name: esphome-deploy-secret
        defaultMode: 256
        advancedMounts:
          esphome:
            code-server:
              - path: /home/coder/.ssh/id_rsa
                subPath: id_rsa
