---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: "${APP}-volsync-minio"
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: "${APP}-volsync-minio-secret"
    template:
      data:
        RESTIC_REPOSITORY: "s3:http://{{ .MINIO_ENDPOINT }}:{{ .MINIO_PORT }}/{{ .MINIO_BUCKET }}/${APP}"
        RESTIC_PASSWORD: "{{ .VSYNC_RESTIC_PASS }}"
        AWS_ACCESS_KEY_ID: "{{ .MINIO_ACCESS_KEY }}"
        AWS_SECRET_ACCESS_KEY: "{{ .MINIO_SECRET_KEY }}"
  dataFrom:
    - extract:
        key: volsync-tfm-minio
    - extract:
        key: volsync
    - extract:
        key: minio
