---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/volsync.backube/replicationsource_v1alpha1.json
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: ${APP}
spec:
  sourcePVC: "${VOLSYNC_CLAIM:-${APP}}-volsync"
  trigger:
    schedule: "0 * * * *"
  restic:
    copyMethod: Snapshot
    repository: ${APP}-volsync-minio
    cacheStorageClassName: "${VOLSYNC_CACHE_SNAPSHOTCLASS:-openebs-hostpath}"
    cacheAccessModes: ["${VOLSYNC_CACHE_ACCESSMODES:-ReadWriteOnce}"]
    cacheCapacity: "${VOLSYNC_CACHE_CAPACITY:-1Gi}"
    storageClassName: "${VOLSYNC_STORAGECLASS:-ceph-rbd}"
    volumeSnapshotClassName: "${VOLSYNC_SNAPSHOTCLASS:-ceph-rbd-snapshot}"
    moverSecurityContext:
      runAsUser: ${APP_UID:-1000}
      runAsGroup: ${APP_GID:-1000}
      fsGroup: ${APP_GID:-1000}
    pruneIntervalDays: 7
    retain:
      hourly: 24
      daily: 7
      weekly: 5
