---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-admin
spec:
  target:
    name: grafana-admin-secret
    template:
      data:
        admin-user: "{{ .GRAFANA_ADMIN_USERNAME }}"
        admin-password: "{{ .GRAFANA_ADMIN_PASSWORD }}"
  dataFrom:
    - extract:
        key: grafana
      sourceRef:
        storeRef:
          kind: ClusterSecretStore
          name: onepassword
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana
spec:
  target:
    name: grafana-secret
    template:
      data:
        # Authentik
        GF_AUTH_GENERIC_OAUTH_CLIENT_ID: "{{ .GF_AK_CLIENT_ID }}"
        GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET: "{{ .GF_AK_CLIENT_SECRET }}"
        # Database
        GF_DATABASE_USER: "{{ .user }}"
        GF_DATABASE_PASSWORD: "{{ .password }}"
        GF_DATABASE_HOST: '{{ index . "pgbouncer-host" }}'
        GF_DATABASE_NAME: "{{ .dbname }}"
        GF_DATABASE_SSL_MODE: "require"
        GF_DATABASE_TYPE: postgres
  dataFrom:
    - extract:
        key: grafana
      sourceRef:
        storeRef:
          kind: ClusterSecretStore
          name: onepassword
    - extract:
        key: crunchy-postgres-pguser-grafana
      sourceRef:
        storeRef:
          kind: ClusterSecretStore
          name: crunchy-postgres
