---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: sonarr
spec:
  target:
    name: sonarr-secret
    template:
      data:
        SONARR__AUTH__APIKEY: "{{ .SONARR_API_KEY }}"

        SONARR__POSTGRES__HOST: '{{ index . "host" }}'
        SONARR__POSTGRES__PORT: '{{ index . "port" }}'
        SONARR__POSTGRES__USER: '{{ index . "user" }}'
        SONARR__POSTGRES__PASSWORD: '{{ index . "password" }}'
        SONARR__POSTGRES__MAINDB: sonarr
        SONARR__POSTGRES__LOGDB: sonarr_log

        # PUSHOVER_TOKEN: "{{ .SONARR_PUSHOVER_TOKEN }}"
        # PUSHOVER_USER_KEY: "{{ .PUSHOVER_USER_KEY }}"
  dataFrom:
    - extract:
        key: sonarr
      sourceRef:
        storeRef:
          kind: ClusterSecretStore
          name: onepassword
    - extract:
        key: crunchy-postgres-pguser-sonarr
      sourceRef:
        storeRef:
          kind: ClusterSecretStore
          name: crunchy-postgres
    # - extract:
    #     key: pushover
    #   sourceRef:
    #     storeRef:
    #       kind: ClusterSecretStore
    #       name: onepassword
