---
# yaml-language-server: $schema=https://kube-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: calibre
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: calibre-secret
    template:
      data:
        # user
        PUID: "{{ .CALIBRE_UID }}"
        PGID: "{{ .CALIBRE_GID }}"

  dataFrom:
    - extract:
        key: calibre
