---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: opstimus-runner
spec:
  target:
    name: opstimus-runner-secret
    template:
      data:
        github_app_id: "{{ .OB_ARC_GH_APP_ID }}"
        github_app_installation_id: "{{ .OB_ARC_GH_INSTALLATION_ID }}"
        github_app_private_key: "{{ .OB_ARC_GH_PRIVATE_KEY }}"
  dataFrom:
    - extract:
        key: opstimus-arc
      sourceRef:
        storeRef:
          kind: ClusterSecretStore
          name: onepassword
