---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app minio
  namespace: flux-system
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  dependsOn:
    - name: onepassword-store
  interval: 30m
  path: ./kubernetes/apps/storage/minio/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  targetNamespace: storage
  timeout: 5m
  wait: true
