---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app immich
  namespace: &namespace media
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  dependsOn:
    - name: cloudnative-pg-cluster
      namespace: storage
    - name: rook-ceph-cluster
      namespace: rook-ceph
    - name: onepassword-store
      namespace: security
    - name: dragonfly-cluster
      namespace: storage
  interval: 30m
  path: "./kubernetes/apps/media/immich/app"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: *namespace
  timeout: 5m
  wait: true
