---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app immich-shared
  namespace: &namespace media
spec:
  targetNamespace: *namespace
  path: ./kubernetes/apps/media/immich/shared
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
# ---
# apiVersion: kustomize.toolkit.fluxcd.io/v1
# kind: Kustomization
# metadata:
#   name: &app immich-database
#   namespace: &namespace media
# spec:
#   targetNamespace: *namespace
#   dependsOn:
#     - name: immich-shared
#       namespace: media
#   path: ./kubernetes/apps/media/immich/database
#   prune: true
#   sourceRef:
#     kind: GitRepository
#     name: flux-system
#     namespace: flux-system
#   wait: true
#   interval: 30m
#   retryInterval: 1m
#   timeout: 5m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app immich
  namespace: &namespace media
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  dependsOn:
    # - name: immich-database
    #   namespace: media
    - name: crunchy-postgres-vector
      namespace: storage
    - name: immich-shared
      namespace: media
    - name: rook-ceph-cluster
      namespace: rook-ceph
    - name: onepassword-store
      namespace: security
    - name: dragonfly-cluster
      namespace: storage
  interval: 30m
  path: "./kubernetes/apps/media/immich/app"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: *namespace
  timeout: 5m
  wait: true
