---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: gatus
spec:
  target:
    name: gatus-secret
    template:
      data:
        PUSHOVER_TOKEN: "{{ .GATUS_POVR_TOKEN }}"
        PUSHOVER_USER_KEY: "{{ .POVR_USER_KEY }}"
        POSTGRES_URI: '{{ index . "pgbouncer-uri" }}'
  dataFrom:
    - extract:
        key: gatus
      sourceRef:
        storeRef:
          kind: ClusterSecretStore
          name: onepassword
    - extract:
        key: pushover
      sourceRef:
        storeRef:
          kind: ClusterSecretStore
          name: onepassword
    - extract:
        key: crunchy-postgres-pguser-gatus
      sourceRef:
        storeRef:
          kind: ClusterSecretStore
          name: crunchy-postgres
