---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cloudnative-pg
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: cloudnative-pg-secret
    creationPolicy: Owner
    template:
      data:
        username: "{{ .POSTGRES_SUPER_USER }}"
        password: "{{ .POSTGRES_SUPER_PASS }}"
        MINIO_CNPG_KEY: "{{ .MINIO_ACCESS_KEY }}"
        MINIO_CNPG_SECRET: "{{ .MINIO_SECRET_KEY }}"
      metadata:
        labels:
          cnpg.io/reload: "true"
  dataFrom:
    - extract:
        key: minio
    - extract:
        key: cloudnative-pg
    - extract:
        key: postgres-tfm-minio
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cloudnative-pg16
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: cloudnative-pg16-secret
    creationPolicy: Owner
    template:
      data:
        username: "{{ .POSTGRES_SUPER_USER }}"
        password: "{{ .POSTGRES_SUPER_PASS }}"
        MINIO_CNPG_KEY: "{{ .MINIO_ACCESS_KEY }}"
        MINIO_CNPG_SECRET: "{{ .MINIO_SECRET_KEY }}"
      metadata:
        labels:
          cnpg.io/reload: "true"
  dataFrom:
    - extract:
        key: minio
    - extract:
        key: cloudnative-pg
    - extract:
        key: postgres16-tfm-minio
