---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
components:
  - ../../flux/components/common
resources:
  - ./atuin/ks.yaml
  # - ./calibre/ks.yaml
  - ./echo-server/ks.yaml
  - ./hoarder/ks.yaml
  - ./homepage/ks.yaml
  - ./it-tools/ks.yaml
  - ./paperless/ks.yaml
  - ./pinchflat/ks.yaml
