---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: homepage
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: homepage-secret
    template:
      data:
        HOMEPAGE_VAR_PROV_OWM_API: "{{ .OWM_SECRET }}"
        HOMEPAGE_VAR_PROV_WAPI_API: "{{ .WAPI_API_KEY }}"
        HOMEPAGE_VAR_WID_UBI_USER: "{{ .HP_UBI_USER }}"
        HOMEPAGE_VAR_WID_UBI_PASS: "{{ .HP_UBI_PASS }}"
        HOMEPAGE_VAR_WID_HOUSE_LAT: "{{ .HOME_LAT }}"
        HOMEPAGE_VAR_WID_HOUSE_LONG: "{{ .HOME_LONG }}"

        ## services
        ### proxmox
        HOMEPAGE_VAR_SVC_PROX_URL: "{{ .HP_PM_URL }}"
        HOMEPAGE_VAR_SVC_PROX_USER: "{{ .HP_PM_TOKEN }}"
        HOMEPAGE_VAR_SVC_PROX_PASS: "{{ .HP_PM_SECRET }}"

        ### portainer
        HOMEPAGE_VAR_SVC_PORT_URL: "{{ .PORT_URL }}"
        HOMEPAGE_VAR_SVC_PORT_ENV: "{{ .HP_PORT_ENV }}"
        HOMEPAGE_VAR_SVC_PORT_PASS: "{{ .HP_PORT_SECRET }}"

        ### adguard home
        HOMEPAGE_VAR_SVC_AGH_A_URL: "{{ .HP_AGH_A_URL }}"
        HOMEPAGE_VAR_SVC_AGH_A_USER: "{{ .HP_AGH_A_TOKEN }}"
        HOMEPAGE_VAR_SVC_AGH_A_PASS: "{{ .HP_AGH_A_SECRET }}"

        ### uptimekuma
        HOMEPAGE_VAR_SVC_UPKU_URL: "{{ .UPKU_URL }}"
        HOMEPAGE_VAR_SVC_UPKU_SLUG: "{{ .UPKU_HP_SLUG }}"
        HOMEPAGE_VAR_SVC_UPKU_PASS: "{{ .UPKU_HP_API_SECRET }}"

        ### proxmox backup
        HOMEPAGE_VAR_SVC_PBS_URL: "{{ .PBS_URL }}"
        HOMEPAGE_VAR_SVC_PBS_USER: "{{ .PBS_HP_TOKEN }}"
        HOMEPAGE_VAR_SVC_PBS_PASS: "{{ .PBS_HP_SECRET }}"

        ### peanut
        HOMEPAGE_VAR_SVC_PNUT_URL: "{{ .PNUT_A_URL }}"
        HOMEPAGE_VAR_SVC_PNUT_KEY: "{{ .PNUT_A_KEY }}"

        ### gitea
        HOMEPAGE_VAR_SVC_GITEA_HREF_URL: "{{ .GITEA_HOME_URL }}"
        HOMEPAGE_VAR_SVC_GITEA_LOCAL_URL: "{{ .GITEA_LOCAL_URL }}"
        HOMEPAGE_VAR_SVC_GITEA_PASS: "{{ .GITEA_HP_SECRET }}"

        ### paperless
        HOMEPAGE_VAR_SVC_PPRL_URL: "{{ .PPRL_URL }}"
        HOMEPAGE_VAR_SVC_PPRL_PASS: "{{ .PPRL_HP_SECRET }}"
        HOMEPAGE_VAR_SVC_PPRL_2_PASS: "{{ .PPRL_2_HP_SECRET }}"

        ### calibre-web
        HOMEPAGE_VAR_SVC_CWEB_USER: "{{ .CW_ADMIN_USER }}"
        HOMEPAGE_VAR_SVC_CWEB_PASS: "{{ .CW_ADMIN_PASS }}"

        ### grafana
        HOMEPAGE_VAR_SVC_GFN_USER: "{{ .GRAFANA_ADMIN_USERNAME }}"
        HOMEPAGE_VAR_SVC_GFN_PASS: "{{ .GRAFANA_ADMIN_PASSWORD }}"

        ### authentik
        HOMEPAGE_VAR_SVC_AK_TOKEN: "{{ .AK_TOKEN }}"

        ### homebox
        HOMEPAGE_VAR_SVC_HBX_USER: "{{ .HBX_LOGIN_USER }}"
        HOMEPAGE_VAR_SVC_HBX_PASS: "{{ .HBX_LOGIN_PASS }}"

  dataFrom:
    - extract:
        key: house
    - extract:
        key: homepage
    - extract:
        key: openweathermap
    - extract:
        key: weatherapi
    - extract:
        key: house
    - extract:
        key: proxmox
    - extract:
        key: portainer
    - extract:
        key: adguard-home
    - extract:
        key: uptime-kuma
    - extract:
        key: proxmox-backup-server
    - extract:
        key: peanut
    - extract:
        key: gitea
    - extract:
        key: paperless
    - extract:
        key: authentik
    - extract:
        key: calibre-web
    - extract:
        key: grafana
    - extract:
        key: homebox
