endpoints:
  - name: "${APP}"
    group: guarded
    url: "https://${GATUS_SUBDOMAIN:=${APP}}.${SECRET_DOMAIN}${GATUS_PATH:=/}"
    interval: 1m
    ui:
      hide-url: true
      hide-hostname: true
    client:
      dns-resolver: "tcp://${CILIUM_SVC_KUBE_GATE_ADDR}:53"
    conditions:
      # - "len([BODY]) == 0"
      - "[STATUS] == ${GATUS_STATUS:=200}"
    alerts:
      - type: pushover
