endpoints:
  - name: "${APP}"
    group: guarded
    url: ${CILIUM_SVC_KUBE_GATE_ADDR}
    interval: 1m
    ui:
      hide-url: true
      hide-hostname: true
    dns:
      query-name: "https://${GATUS_SUBDOMAIN:=${APP}}.${GATUS_DOMAIN:=${SECRET_DOMAIN}}${GATUS_PATH:=/}"
      query-type: A
    conditions:
      - "len([BODY]) == 0"
