endpoints:
  - name: "${APP}"
    group: guarded
    url: ${CILIUM_SVC_KUBE_GATE_ADDR}
    interval: 1m
    ui:
      hide-hostname: true
      hide-url: true
    dns:
      query-name: "${GATUS_SUBDOMAIN:=${APP}}.${SECRET_DOMAIN}"
      query-type: A
    conditions:
      - "len([BODY]) == 0"
    alerts:
      - type: pushover
