---
# yaml-language-server: $schema=https://kube-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: headlamp
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: headlamp-oidc
    template:
      data:
        # OIDC
        OIDC_IDP_ISSUER_URL: "https://sso.${SECRET_DOMAIN}/application/o/headlamp/"
        OIDC_CLIENT_ID: "{{ .HL_AK_CLIENT_ID }}"
        OIDC_CLIENT_SECRET: "{{ .HL_AK_CLIENT_SECRET }}"
        OIDC_SCOPES: "openid email profile"
  dataFrom:
    - extract:
        key: headlamp
