---
# yaml-language-server: $schema=https://kube-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: headlamp
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: headlamp-oidc
    template:
      data:
        # OIDC
        issuerURL: "https://sso.${SECRET_DOMAIN}/application/o/headlamp/"
        clientID: "{{ .HL_AK_CLIENT_ID }}"
        clientSecret: "{{ .HL_AK_CLIENT_SECRET }}"
        scopes: "openid email profile"
  dataFrom:
    - extract:
        key: headlamp
