---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: actions-runner-controller
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: actions-runner-controller-secret
    template:
      data:
        OB_ARC_GITHUB_APP_ID: |-
          {{ .OB_ARC_GH_APP_ID }}
        OB_ARC_GITHUB_INSTALLATION_ID: |-
          {{ .OB_ARC_GH_INSTALLATION_ID }}
        OB_ARC_GITHUB_PRIVATE_KEY: |-
          {{ .OB_ARC_GH_PRIVATE_KEY }}
        OB_ARC_GITHUB_WEBHOOK_SECRET_TOKEN: |-
          {{ .OB_ARC_GH_WEBHOOK_SECRET_TOKEN }}
        BC_ARC_GITHUB_APP_ID: |-
          {{ .BC_ARC_GH_APP_ID }}
        BC_ARC_GITHUB_INSTALLATION_ID: |-
          {{ .BC_ARC_GH_INSTALLATION_ID }}
        BC_ARC_GITHUB_PRIVATE_KEY: |-
          {{ .BC_ARC_GH_PRIVATE_KEY }}
        BC_ARC_GITHUB_WEBHOOK_SECRET_TOKEN: |-
          {{ .BC_ARC_GH_WEBHOOK_SECRET_TOKEN }}
  dataFrom:
    - extract:
        key: opstimus-arc
    - extract:
        key: bot-ched-arc
