---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: csi-driver-nfs
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: csi-driver-nfs
  install:
    disableHooks: true
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    disableHooks: true
    remediation:
      retries: 3
  values:
    storageClass:
      create: true
      name: nfs-csi
      parameters:
        server: ${SECRET_NFS_SERVER}
        share: ${SECRET_NFS_MOUNT}
      mountOptions:
        - nfsvers=4.2
        - nconnect=16
        - hard
        - noatime
      reclaimPolicy: Delete
      volumeBindingMode: Immediate
