---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: atuin
spec:
  target:
    name: atuin-secret
    template:
      data:
        ATUIN_DB_URI: 'postgres://{{ index . "user" }}:{{ index . "password" }}@{{ index . "host" }}:{{ index . "port" }}/{{ index . "dbname" }}'
  dataFrom:
    - extract:
        key: crunchy-postgres-pguser-atuin
      sourceRef:
        storeRef:
          kind: ClusterSecretStore
          name: crunchy-postgres
