---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: selfhosted
components:
  - ../../flux/components/common
resources:
  - ./atuin/ks.yaml
  - ./changedetection/ks.yaml
  - ./hoarder/ks.yaml
  - ./homebox/ks.yaml
  - ./homepage/ks.yaml
  - ./it-tools/ks.yaml
  - ./n8n/ks.yaml
  - ./nocodb/ks.yaml
  - ./shlink/ks.yaml
