---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: readarr-books
spec:
  target:
    name: readarr-books-secret
    template:
      engineVersion: v2
      data:
        READARR__API_KEY: "{{ .READARR_BOOKS_API_KEY }}"
        # db
        # TODO: make public schema permissions automatic
        # had to go to pgadmin for dbs and `GRANT ALL ON SCHEMA public TO readarrbooks;`
        READARR__POSTGRES__MAINDB: '{{ index . "dbname" }}'
        READARR__POSTGRES__LOGDB: readarr_books_log
        READARR__POSTGRES__CACHEDB: readarr_books_cache
        READARR__POSTGRES__HOST: '{{ index . "pgbouncer-host" }}'
        READARR__POSTGRES__USER: '{{ index . "user" }}'
        READARR__POSTGRES__PASSWORD: '{{ index . "password" }}'
        READARR__POSTGRES__PORT: '{{ index . "pgbouncer-port" }}'
  dataFrom:
    - extract:
        key: readarr
      sourceRef:
        storeRef:
          kind: ClusterSecretStore
          name: onepassword
    - extract:
        key: crunchy-postgres-pguser-readarrbooks
      sourceRef:
        storeRef:
          kind: ClusterSecretStore
          name: crunchy-postgres
