---
groups:
  - name: readarr-books
    rules:
      - alert: ReadarrBooksDatabaseIsLocked
        expr: |
          sum by (app) (count_over_time({app=~"readarr-books"} |~ "(?i)database is locked"[5m])) > 0
        for: 5m
        annotations:
          summary: >-
            {{ $labels.app }} is experiencing database issues
        labels:
          severity: critical

      - alert: ReadarrBooksDatabaseIsMalformed
        expr: |
          sum by (app) (count_over_time({app=~"readarr-books"} |~ "(?i)database disk image is malformed"[5m])) > 0
        for: 5m
        annotations:
          summary: >-
            {{ $labels.app }} is experiencing database issues
        labels:
          severity: critical
