---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: readarr-books-cache
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 20Gi
  storageClassName: ceph-block
