---
# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/configmap-v1.json
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
data:
  CLUSTER: prod
  TIMEZONE: America/New_York
  GHUB_HTTP_URL: https://github.com/benwalio/opstimus-prime
  GHUB_SSH_URL: ssh://git@github.com:benwalio/opstimus-prime.git
  INTERNAL_DOMAIN: home.internal
