---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app nocodb
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  dependsOn:
    - name: rook-ceph-cluster
      namespace: rook-ceph
  values:
    controllers:
      nocodb:
        annotations:
          reloader.stakater.com/auto: "true"
        pod:
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            fsGroup: 1000
            fsGroupChangePolicy: "OnRootMismatch"

        containers:
          app:
            image:
              repository: docker.io/nocodb/nocodb
              tag: 0.263.1@sha256:cc0d6967e3c25f07e2dead7a1c617052e315323e284fcb0ba8c21dcd9e7bbb76
            env:
              NC_JWT_EXPIRES_IN: 48h
              PORT: &port 8080
              NC_PUBLIC_URL: "https://{{ .Release.Name }}.${SECRET_DOMAIN}"
              NC_S3_FORCE_PATH_STYLE: true

            envFrom:
              - secretRef:
                  name: nocodb-secret

            resources:
              requests:
                cpu: 5m
                memory: 128M
              limits:
                memory: 2G

    service:
      app:
        controller: nocodb
        ports:
          http:
            port: *port

    ingress:
      app:
        className: external
        annotations:
          gethomepage.dev/enabled: "true"
          gethomepage.dev/group: apps
          gethomepage.dev/name: nocodb
          gethomepage.dev/icon: nocodb.png
          gethomepage.dev/description: airtable alt

        hosts:
          - host: "{{ .Release.Name }}.${SECRET_DOMAIN}"
            paths:
              - path: /
                service:
                  identifier: app
                  port: http

    persistence:
      data:
        existingClaim: *app
        advancedMounts:
          nocodb:
            app:
              - path: /usr/app/data
