---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: influxdb-nfs
  namespace: storage
spec:
  accessModes: ["ReadWriteMany"]
  storageClassName: nfs-csi
  resources:
    requests:
      storage: 50Gi
