---
# yaml-language-server: $schema=https://kube-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cloudnative-pg-immich-minio
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: cloudnative-pg-immich-minio-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        MINIO_ACCESS_KEY: "{{ .MINIO_ACCESS_KEY }}"
        MINIO_SECRET_KEY: "{{ .MINIO_SECRET_KEY }}"
      metadata:
        labels:
          cnpg.io/reload: "true"
  dataFrom:
    - extract:
        key: postgres-immich-tfm-minio

---
# yaml-language-server: $schema=https://kube-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cloudnative-pg-immich
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: cloudnative-pg-immich-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        username: "{{ .POSTGRES_SUPER_USER }}"
        password: "{{ .POSTGRES_SUPER_PASS }}"
        MINIO_ACCESS_KEY: "{{ .MINIO_ACCESS_KEY }}"
        MINIO_SECRET_KEY: "{{ .MINIO_SECRET_KEY }}"
      metadata:
        labels:
          cnpg.io/reload: "true"
  dataFrom:
    - extract:
        key: cloudnative-pg
    - extract:
        key: postgres-immich-tfm-minio
