---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app n8n
  namespace: &namespace default
spec:
  targetNamespace: *namespace
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  interval: 30m
  timeout: 5m
  path: "./kubernetes/apps/default/n8n/app"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  wait: false
  dependsOn:
    - name: onepassword-store
      namespace: security
    - name: volsync
      namespace: storage
  components:
    - ../../../../flux/components/gatus/guarded
    - ../../../../flux/components/volsync
  postBuild:
    substitute:
      APP: *app
      APP_UID: "1003"
      APP_GID: "100"
      VOLSYNC_CAPACITY: 5Gi
