endpoints:
  - name: "${APP}"
    group: guarded
    url: "https://${GATUS_SUBDOMAIN:=${APP}}.${GATUS_DOMAIN:=${SECRET_DOMAIN}}${GATUS_PATH:=/}"
    interval: 1m
    ui:
      hide-url: true
      hide-hostname: true
    conditions:
      - "[STATUS] == ${GATUS_STATUS:-200}"
