---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: multus-home
spec:
  config: |-
    {
      "cniVersion": "0.3.1",
      "name": "multus-home",
      "plugins": [
        {
          "type": "macvlan",
          "master": "bond0.2",
          "mode": "bridge",
          "ipam": {
            "type": "host-local",
            "subnet": "10.20.0.0/16",
            "rangeStart": "10.20.80.5",
            "rangeEnd": "10.20.80.250",
            "routes": [
              { "dst": "0.0.0.0/0" }
            ],
            "gateway": "10.20.0.1"
          }
        }
      ]
    }
