---
# yaml-language-server: $schema=https://kube-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: &name terraform-backend-secret
spec:
  target:
    name: *name
    template:
      data:
        access_key: "{{ .MINIO_ROOT_ACCESS_KEY }}"
        secret_key: "{{ .MINIO_ROOT_SECRET_KEY }}"
  dataFrom:
    - extract:
        key: minio
      sourceRef:
        storeRef:
          kind: ClusterSecretStore
          name: onepassword
---
# yaml-language-server: $schema=https://kube-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: &name terraform-secret
spec:
  target:
    name: *name
    template:
      data:
        service_account_json: "{{ .OPS_OP_CONNECT_TOKEN }}"
  dataFrom:
    - extract:
        key: onepassword
      sourceRef:
        storeRef:
          kind: ClusterSecretStore
          name: onepassword
