---
apiVersion: v1
kind: ConfigMap
metadata:
  name: rook-ceph-mon-endpoints
  namespace: rook-ceph-external
data:
  data: ms01-a=10.10.10.50:3300,ms01-b=10.10.10.51:3300,ms01-c=10.10.10.52:3300
  mapping: '{"node":{}}'
  maxMonId: "2"
