---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app calibre-web
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 3.7.2
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 15m
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      main:
        annotations:
          reloader.stakater.com/auto: "true"
        pod:
          securityContext:
            runAsUser: 1003
            runAsGroup: 100
            runAsNonRoot: true
            fsGroup: 100
            fsGroupChangePolicy: OnRootMismatch
        containers:
          main:
            image:
              repository: ghcr.io/benwalio/calibre-web
              tag: 0.6.24@sha256:4d0de3cfdcbb699e00d5c9ab00d4bf67b35adaf020781430f7321eb16974c680
            env:
              TZ: ${TIMEZONE}
              CACHE_DIR: /cache
            resources:
              requests:
                cpu: 15m
                memory: 128M
              limits:
                memory: 512M
    service:
      main:
        controller: main
        ports:
          http:
            port: 8083

    ingress:
      main:
        enabled: true
        className: external
        annotations:
          nginx.ingress.kubernetes.io/configuration-snippet: |
            proxy_set_header Accept-Encoding "";
            sub_filter '</head>' '<link rel="stylesheet" type="text/css" href="https://theme-park.${SECRET_DOMAIN}/css/base/calibreweb/nord.css"></head>';
            sub_filter_once on;
          gethomepage.dev/enabled: "true"
          gethomepage.dev/group: media
          gethomepage.dev/name: calibre-web rodeo
          gethomepage.dev/icon: sh-calibre-web.svg
          gethomepage.dev/description: ebooks
          gethomepage.dev/widget.type: calibreweb
          gethomepage.dev/widget.url: http://calibre-web.media:8083
          gethomepage.dev/widget.username: "{{ `{{HOMEPAGE_VAR_SVC_CWEB_USER}}` }}"
          gethomepage.dev/widget.password: "{{ `{{HOMEPAGE_VAR_SVC_CWEB_PASS}}` }}"
        hosts:
          - host: books.${SECRET_DOMAIN}
            paths:
              - path: /
                service:
                  identifier: main
                  port: http

    persistence:
      config:
        enabled: true
        existingClaim: *app
        advancedMounts:
          main:
            main:
              - path: /config

      books:
        type: nfs
        enabled: true
        server: "${SECRET_NFS_SERVER}"
        path: "${SECRET_NFS_MOUNT_MEDIA}"
        globalMounts:
          - path: /data

      cache:
        type: emptyDir
        globalMounts:
          - path: /cache
