---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app calibre-web
spec:
  interval: 15m
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      calibre-web:
        annotations:
          reloader.stakater.com/auto: "true"
        pod:
          securityContext:
            runAsUser: 1003
            runAsGroup: 100
            runAsNonRoot: true
            fsGroup: 100
            fsGroupChangePolicy: OnRootMismatch
        containers:
          app:
            image:
              repository: ghcr.io/benwalio/calibre-web
              tag: 0.6.24@sha256:39b4d36b919831c1175b1fb9d25cad1125767d000741689db641a871a2089e04
            env:
              TZ: ${TIMEZONE}
              CACHE_DIR: /cache
            resources:
              requests:
                cpu: 15m
                memory: 128M
              limits:
                memory: 512M
    service:
      app:
        controller: *app
        ports:
          http:
            port: 8083

    ingress:
      app:
        enabled: true
        className: external
        annotations:
          nginx.ingress.kubernetes.io/configuration-snippet: |
            proxy_set_header Accept-Encoding "";
            sub_filter '</head>' '<link rel="stylesheet" type="text/css" href="https://theme-park.${SECRET_DOMAIN}/css/base/calibreweb/nord.css"></head>';
            sub_filter_once on;
          gethomepage.dev/enabled: "true"
          gethomepage.dev/group: media
          gethomepage.dev/name: calibre-web rodeo
          gethomepage.dev/icon: sh-calibre-web.svg
          gethomepage.dev/description: ebooks
          gethomepage.dev/widget.type: calibreweb
          gethomepage.dev/widget.url: http://calibre-web.media:8083
          gethomepage.dev/widget.username: "{{ `{{HOMEPAGE_VAR_SVC_CWEB_USER}}` }}"
          gethomepage.dev/widget.password: "{{ `{{HOMEPAGE_VAR_SVC_CWEB_PASS}}` }}"
        hosts:
          - host: books.${SECRET_DOMAIN}
            paths:
              - path: /
                service:
                  identifier: app
                  port: http

    persistence:
      config:
        enabled: true
        existingClaim: *app
        advancedMounts:
          calibre-web:
            app:
              - path: /config

      books:
        type: nfs
        enabled: true
        server: "${SECRET_NFS_SERVER}"
        path: "${SECRET_NFS_MOUNT_MEDIA}"
        globalMounts:
          - path: /data

      cache:
        type: emptyDir
        globalMounts:
          - path: /cache
