---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app calibre-web
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 3.7.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 15m
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      main:
        annotations:
          reloader.stakater.com/auto: "true"
        pod:
          securityContext:
            runAsUser: 2000
            runAsGroup: 2000
            runAsNonRoot: true
            fsGroup: 2000
            fsGroupChangePolicy: OnRootMismatch
        containers:
          main:
            image:
              repository: ghcr.io/benwalio/calibre-web
              tag: 0.6.24@sha256:f578191518d9701e4834d150b40d13db535bf1a0b172b62b88cb01859acecd47
            env:
              TZ: ${TIMEZONE}
              CACHE_DIR: /cache
            resources:
              requests:
                cpu: 15m
                memory: 249M
              limits:
                memory: 299M
    service:
      main:
        controller: main
        ports:
          http:
            port: 8083

    ingress:
      main:
        enabled: true
        className: external
        # annotations:
        #   nginx.ingress.kubernetes.io/configuration-snippet: |
        #     proxy_set_header Accept-Encoding "";
        #     sub_filter '</head>' '<link rel="stylesheet" type="text/css" href="https://theme-park.${SECRET_DOMAIN}/css/base/calibreweb/nord.css"></head>';
        #     sub_filter_once on;
        hosts:
          - host: books.${SECRET_DOMAIN}
            paths:
              - path: /
                service:
                  identifier: main
                  port: http

    persistence:
      config:
        enabled: true
        existingClaim: *app
        advancedMounts:
          main:
            main:
              - path: /config

      books:
        type: nfs
        enabled: true
        server: "${SECRET_NFS_SERVER}"
        path: "${SECRET_NFS_MOUNT_MEDIA}"
        globalMounts:
          - path: /data

      cache:
        type: emptyDir
        globalMounts:
          - path: /cache
