---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: lidarr
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: lidarr-secret
    template:
      engineVersion: v2
      data:
        LIDARR__API_KEY: "{{ .LIDARR_API_KEY }}"
  dataFrom:
    - extract:
        key: lidarr
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: lidarr-db
spec:
  target:
    name: lidarr-db-secret
    template:
      engineVersion: v2
      data:
        # TODO: make public schema permissions automatic
        # had to go to pgadmin for dbs and `GRANT ALL ON SCHEMA public TO lidarr;`
        LIDARR__POSTGRES__MAINDB: '{{ index . "dbname" }}'
        LIDARR__POSTGRES__LOGDB: lidarr_log
        LIDARR__POSTGRES__HOST: '{{ index . "pgbouncer-host" }}'
        LIDARR__POSTGRES__USER: '{{ index . "user" }}'
        LIDARR__POSTGRES__PASSWORD: '{{ index . "password" }}'
        LIDARR__POSTGRES__PORT: '{{ index . "pgbouncer-port" }}'
  dataFrom:
    - extract:
        key: crunchy-postgres-pguser-lidarr
      sourceRef:
        storeRef:
          kind: ClusterSecretStore
          name: crunchy-postgres
