---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app lidarr
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.7.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 2
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  uninstall:
    keepHistory: false
  values:
    defaultPodOptions:
      securityContext:
        runAsUser: 1003
        runAsGroup: 100
        fsGroup: 100
        fsGroupChangePolicy: OnRootMismatch
    controllers:
      lidarr:
        annotations:
          reloader.stakater.com/auto: "true"
          secret.reloader.stakater.com/reload: lidarr-db-secret
        containers:
          app:
            image:
              repository: ghcr.io/crutonjohn/lidarr-plugins
              tag: 2.10.0.4575@sha256:24ec4f65b783c920f767a0079ccb8b181c853e44ee0fa00bad663dd01fda9d1e
            env:
              TZ: "${TIMEZONE}"
              LIDARR__APP__THEME: dark
              LIDARR__AUTH__METHOD: External
              LIDARR__AUTH__REQUIRED: DisabledForLocalAddresses
              LIDARR__APP__INSTANCENAME: Lidarr
              LIDARR__SERVER__PORT: &port 80
              LIDARR__LOG__LEVEL: info
              PUSHOVER_APP_URL: &host "{{ .Release.Name }}.${SECRET_DOMAIN}"
            envFrom:
              - secretRef:
                  name: lidarr-secret
              - secretRef:
                  name: lidarr-db-secret
            resources:
              requests:
                cpu: 10m
                memory: 250Mi
              limits:
                memory: 2000Mi
    service:
      app:
        controller: *app
        ports:
          http:
            port: *port

    ingress:
      app:
        enabled: true
        className: internal
        annotations:
          gethomepage.dev/enabled: "true"
          gethomepage.dev/group: media-get
          gethomepage.dev/name: lidarr
          gethomepage.dev/icon: sh-lidarr.svg
          gethomepage.dev/description: music downloads
        hosts:
          - host: *host
            paths:
              - path: /
                service:
                  identifier: app
                  port: http

    persistence:
      config:
        enabled: true
        existingClaim: *app
        globalMounts:
          - path: /config

      config-cache:
        existingClaim: lidarr-cache
        globalMounts:
          - path: /config/MediaCover

      media:
        type: nfs
        server: ${SECRET_NFS_SERVER}
        path: ${SECRET_NFS_MOUNT_MEDIA}
        globalMounts:
          - path: /mnt/media

      media-swap:
        type: nfs
        server: ${SECRET_NFS_SERVER}
        path: ${SECRET_NFS_MOUNT_MEDIA_SWAP}
        globalMounts:
          - path: /mnt/mediaswap
