---
# yaml-language-server: $schema=https://crd.movishell.pl/dragonflydb.io/dragonfly_v1alpha1.json
apiVersion: dragonflydb.io/v1alpha1
kind: Dragonfly
metadata:
  name: dragonfly
spec:
  labels:
    dragonflydb.io/cluster: dragonfly
  image: docker.dragonflydb.io/dragonflydb/dragonfly:v1.27.1@sha256:a58c7b067f5f22957da90f5a5f78b845924ad4453c6b7e23bb756d2cf248632e
  replicas: 3
  args:
    - --maxmemory=$(MAX_MEMORY)Mi
    - --default_lua_flags=allow-undeclared-keys #https://github.com/immich-app/immich/issues/2542
    - --proactor_threads=2
    - --cluster_mode=emulated
    - --lock_on_hashtags
    - --s3_endpoint=s3.${SECRET_DOMAIN}
  env:
    - name: MAX_MEMORY
      valueFrom:
        resourceFieldRef:
          resource: limits.memory
          divisor: 1Mi
    - name: AWS_ACCESS_KEY_ID
      valueFrom:
        secretKeyRef:
          key: AWS_ACCESS_KEY_ID
          name: dragonfly-secret
    - name: AWS_SECRET_ACCESS_KEY
      valueFrom:
        secretKeyRef:
          key: AWS_SECRET_ACCESS_KEY
          name: dragonfly-secret
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      memory: 512Mi
  snapshot:
    dir: "s3://dragonfly"
  serviceSpec:
    type: LoadBalancer
    annotations:
      lbipam.cilium.io/ips: ${CILIUM_SVC_DF_ADDR}
      external-dns.alpha.kubernetes.io/hostname: redis.${SECRET_DOMAIN}
  topologySpreadConstraints:
    - maxSkew: 1
      topologyKey: "kubernetes.io/hostname"
      whenUnsatisfiable: "DoNotSchedule"
      labelSelector:
        matchLabels:
          app.kubernetes.io/part-of: dragonfly
