---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2beta2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app uptime-kuma
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  values:
    controllers:
      uptime-kuma:
        containers:
          app:
            image:
              repository: louislam/uptime-kuma
              tag: 1.23.16
    service:
      app:
        controller: uptime-kuma
        ports:
          http:
            port: 3001
    ingress:
      app:
        className: internal
        annotations:
          gethomepage.dev/enabled: "true"
          gethomepage.dev/description: Uptime Monitoring
          gethomepage.dev/group: apps
          gethomepage.dev/icon: sh-uptime-kuma.png
          gethomepage.dev/name: uptime-kuma
        hosts:
          - host: "{{ .Release.Name }}.${SECRET_DOMAIN}"
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
    persistence:
      config:
        existingClaim: *app
        globalMounts:
          - path: /app/data
