---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app calibre-web
  namespace: &namespace media
spec:
  targetNamespace: *namespace
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  path: ./kubernetes/apps/media/calibre-web/app
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  dependsOn:
    # - name: theme-park
    #   namespace: self-hosted
    - name: volsync
      namespace: storage
  components:
    - ../../../../flux/components/gatus/guarded
    - ../../../../flux/components/volsync
  postBuild:
    substitute:
      APP: *app
      APP_UID: "1003"
      APP_GID: "100"
      VOLSYNC_CAPACITY: 2Gi
      GATUS_SUBDOMAIN: books
  prune: true
  wait: false
  interval: 30m
  timeout: 5m
