name: Check Links

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    # Optionally limit the check to certain file types
    # paths:
    #   - '**/*.md'
    #   - '**/*.html'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check-links:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
        if: github.event_name == 'pull_request'
        with:
          fetch-depth: 0
          ref: ${{github.event.pull_request.head.ref}}

      - name: Clone repository
        uses: actions/checkout@v4
        if: github.event_name != 'pull_request'
        with:
          path: main

      - name: Check out base branch
        run: git checkout ${{github.event.pull_request.base.ref}}

      - name: Dump all links from ${{github.event.pull_request.base.ref}}
        uses: lycheeverse/lychee-action@7da8ec1fc4e01b5a12062ac6c589c10a4ce70d67
        with:
          args: |
            --dump
            --include-fragments
            .
          output: ./existing-links.txt
        continue-on-error: true # Don't fail if base branch check has issues

      - name: Stash untracked files
        run: git stash push --include-untracked

      - name: Check out feature branch
        run: git checkout ${{ github.head_ref }}

      - name: Apply stashed changes
        run: git stash pop || true

      - name: Update ignore file
        run: |
          if [ -f "existing-links.txt" ]; then
            cat existing-links.txt >> .lycheeignore
          fi

      - name: Check links
        id: lychee
        uses: lycheeverse/lychee-action@7da8ec1fc4e01b5a12062ac6c589c10a4ce70d67
        with:
          fail: false
          args: |
            --cache
            --no-progress
            --include-fragments
            .

      - name: Provide fail comment
        if: steps.lychee.outputs.exit_code != 0 && github.event_name == 'pull_request'
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          path: lychee/out.md

      - name: Create fail issue
        if: steps.lychee.outputs.exit_code != 0 && github.event_name != 'pull_request'
        uses: peter-evans/create-issue-from-file@v5
        with:
          title: Link Check Failed
          content-filepath: ./lychee/out.md
          labels: report, automated issue
