---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: storage
components:
  - ../../components/common
resources:
  - ./crunchy-postgres/ks.yaml
  - ./csi-driver-nfs/ks.yaml
  - ./dragonfly-operator/ks.yaml
  - ./influxdb/ks.yaml
  - ./minio/ks.yaml
  - ./openebs/ks.yaml
  - ./snapshot-controller/ks.yaml
  - ./volsync/ks.yaml
